### ISSUE TITLE
XML organization and tags

### ISSUE THREAD

**Issue by kbartelt** [Riverscapes/RIM#4]
@philipbaileynar @joewheaton I'm a bit confused about the organization of the project.rs xml and xml tags. I have a few specific questions and points of confusion below:

1. Does the order of files within the xml matter, or only the organization of where items are nested within tags? Can the structure of the xml and tags be completely different than the structure of the project folder on my disk or should this be organized similarly?

2. I'm struggling to understand where a Realization could fit in within an inundation project type. Do realizations always need to have the same components or can there be different types of realizations? 

For example, I could imagine the following things to all be realizations of different types:

- Data Capture Events (DCEs): 
DCEs are intermediate or mapping layers. There is a new DCE with each different input imagery date or type, or a different person mapping

- Riverscape context mapped layers  :
This is basically just the valley bottom extent. This typically wouldn't change over time like DCEs would but might change based on who mapped it or if unedited VBET output were used

- Outputs
The outputs I calculate right now are (a) summary metrics and a plot for just a single DCE and Valley bottom polygon (b) changes in metrics and a plot for 2 different DCEs and (c) metrics averaged over all or multiple selected DCEs (helpful for my thesis to make cross-site comparisons). 

3. If I do need to use tags that do not exist, should I make edits to the XSD and save that locally in the project folder? Is this generally something I should try hard to avoid or is creating new tags not a big deal?

Thank you for the help.

**Comment by philipbaileynar** [comment]
The project.rs.xml is an imperfect system that we conceived three or four years ago as a reaction to urgent needs in CHaMP. It includes some good ideas, but we know we really need to revisit it, especially realizations, a term that I stole from the simulation modeling literature. Our use of the term realizations is only half baked, as evidenced by its misuse in several of our existing project types. We intend to revisit the project.rs.xml and it will likely change in the future. But when we do we will automate the process of migrating all existing project.rs.xml files to the new system, so any effort spent today producing these files is definitely not time wasted.

Specific responses:

* The sequence of items in the project.rs.xml file does **not** matter.
* The structure of the tags does **not** need to perfectly match your folder structure. That said, keeping the two similar reduces confusion and speeds up comprehension by new users.
* Ignore realizations if you don't need them. Matt and I wrestle with them every time we invent a new project type. Theoretically any process (performed either manually or by code) that changes data can be considered to be a separate type of realization. In multi-step models like yours this might mean that there are a dozen or more different types of realization. Simpler models like VBET are easier because they really just produce one type of output.
* You can use new tags if you insist, but we tend to reserve them for concepts that apply across several models (e.g. \<DEM\>) rather than concepts that are bespoke to a single model. In your Mill Creek example I like your use of new tags for \<PDF\> and \<DCE\> because I foresee them being useful other places. I am less keen on the \<Mapping\> because its simultaneously vague (mapping what?) and bespoke to your inundation model (so far). I know @joewheaton will probably argue that "user interpretation mapping" is an integral part of applying any riverscape modeled results but until we have more examples I don't think we can say that we have this distilled down to its core meaning and run with this concept yet.

**Comment by joewheaton** [comment]
Great questions @kbartelt and really helpful responses @philipbaileynar. 

Re:

> Our use of the term realizations is only half baked

I struggled with this and the way I thought (but understand now we are not) using realizations was for any example where I might have multiple of the same type of thing. In the business logic, I think you call this a `<Repeater>`. I think GCD will be a great test of this. If we can't figure out a way to make realizations or repeaters work on making the riverscapes project and business logic there, then we'll be in trouble.

Re: 

> I like your use of new tags for <PDF> and <DCE> because I foresee them being useful other places. I am less keen on the <Mapping> because its simultaneously vague (mapping what?) and bespoke to your inundation model (so far). I know @joewheaton will probably argue that "user interpretation mapping" is an integral part of applying any riverscape modeled results but until we have more examples

Actually, I am with you on this. This is what business logic and name labels allow a programmer to customize. No need to invent new tags unnecessarily.

**Comment by MattReimer** [comment]
@philipbaileynar not to be pedantic but sequence of nodes in XML **may** matter.

For example, when `xs:sequence` is used the order matters.

When designing you project.rs.xml file you need to take this into consideration and make choices based on how your xml will be used.

**Comment by kbartelt** [comment]
Thanks all for providing clarification on this. I'll keep the <DCE> and <PDF> tags but will change <Mapping> to <Realizations>.

**Comment by joewheaton** [comment]
@nick4rivers you may find some of this interesting... I'm closing issue.
